export const locationsData = [
  {
    region: "Tashkent city",
    districts: {
      bektemir: "Bektemir tumani",
      chilonzor: "Chilonzor tumani",
      shaykhontohur: "Shaykhontohur tumani",
      yunusobod: "Yunusobod tumani",
      yakkasaroy: "Yakkasaroy tumani",
      mirzo_ulugbek: "Mirzo Ulugbek tumani",
      sergeli: "Sergeli tumani",
      uchtepa: "Uchtepa tumani",
      mirobod: "Mirobod tumani",
      olmazor: "Olmazor tumani",
      yashnobod: "Yashnobod tumani",
      hamza: "Hamza (Yashnobod) tumani",
    },
  },
  {
    region: "Tashkent",
    districts: {
      bekobod: "Bekobod tumani",
      bostonliq: "Bostonliq tumani",
      boqobod: "Boqobod tumani",
      chirchiq: "Chirchiq tumani",
      chinoz: "Chinoz tumani",
      ohangaron: "Ohangaron tumani",
      parkent: "Parkent tumani",
      piskent: "Piskent tumani",
      quyichirchiq: "Quyi Chirchiq tumani",
      yuqorichirchiq: "Yuqori Chirchiq tumani",
      oqqo_rg_on: "Oqqo‘rg‘on tumani",
      yangiobod: "Yangiobod tumani",
      yangiyo_l: "Yangiyo‘l tumani",
      zangiota: "Zangiota tumani",
      nurafshon: "Nurafshon tumani",
    },
  },
  {
    region: "Andijon",
    districts: {
      andijon: "Andijon tumani",
      asaka: "Asaka tumani",
      buloqboshi: "Buloqboshi tumani",
      jalaquduq: "Jalaquduq tumani",
      xalqobod: "Xalqobod tumani",
      qorasuv: "Qorasuv tumani",
      shahrikhon: "Shahrikhon tumani",
      ulugnor: "Ulugnor tumani",
      xoroson: "Xo‘jaobod tumani",
      qo_rqon: "Qo‘rg‘ontepa tumani",
      marhamat: "Marhamat tumani",
    },
  },
  {
    region: "Buxoro",
    districts: {
      buxoro: "Buxoro tumani",
      g_ijduvon: "G‘ijduvon tumani",
      k_ogon: "Kogon tumani",
      romitan: "Romitan tumani",
      qorako_l: "Qorako‘l tumani",
      vobkent: "Vobkent tumani",
      shofirkon: "Shofirkon tumani",
      oltinso: "Olot tumani",
    },
  },
  {
    region: "Farg'ona",
    districts: {
      farg_ona: "Farg‘ona tumani",
      marg_ilon: "Marg‘ilon tumani",
      rishton: "Rishton tumani",
      oltiariq: "Oltiariq tumani",
      quva: "Quva tumani",
      so_x: "So‘x tumani",
      dang_ara: "Dang‘ara tumani",
      boston: "Buvayda tumani",
    },
  },
  {
    region: "Jizzax",
    districts: {
      jizzax: "Jizzax tumani",
      zafarobod: "Zafarobod tumani",
      do_lex: "Do‘lex tumani",
      mingbuloq: "Mingbuloq tumani",
      arnasoy: "Arnasoy tumani",
      gallaorol: "G‘allaorol tumani",
      forish: "Forish tumani",
    },
  },
  {
    region: "Kashkadarya",
    districts: {
      kitob: "Kitob tumani",
      denov: "Denov tumani",
      shahrisabz: "Shahrisabz tumani",
      nishon: "Nishon tumani",
      koshkidar: "Koshkidar tumani",
      qazilqum: "Qazilqum tumani",
      qamishqir: "Qamishqir tumani",
    },
  },
  {
    region: "Khorezm",
    districts: {
      urganch: "Urganch tumani",
      beruniy: "Beruniy tumani",
      xazorasp: "Xazorasp tumani",
      shavat: "Shavat tumani",
      khiva: "Khiva tumani",
      yuzbekistan: "Yuzbekistan tumani",
    },
  },
  {
    region: "Navoiy",
    districts: {
      navoi: "Navoi tumani",
      zafarabad: "Zafarabad tumani",
      konimex: "Konimex tumani",
      nurabad: "Nurabad tumani",
      kyzyltepa: "Kyzyltepa tumani",
      uchquduq: "Uchquduq tumani",
      navoiy: "Navoiy tumani",
    },
  },
  {
    region: "Namangan",
    districts: {
      namangan: "Namangan tumani",
      chortoq: "Chortoq tumani",
      pap: "Pap tumani",
      uychi: "Uychi tumani",
      norin: "Norin tumani",
      kosonsoy: "Kosonsoy tumani",
      buz: "Buz tumani",
    },
  },
  {
    region: "Surxondaryo",
    districts: {
      termiz: "Termiz tumani",
      boysun: "Boysun tumani",
      uzun: "Uzun tumani",
      sherkhan: "Sherkhan tumani",
      jarkurgan: "Jarkurgan tumani",
      mazari: "Mazari tumani",
    },
  },
  {
    region: "Sirdaryo",
    districts: {
      gulistan: "Gulistan tumani",
      sirdaryo: "Sirdaryo tumani",
      boyovut: "Boyovut tumani",
      mirzachul: "Mirzachul tumani",
      shag_ayb: "Shag‘ayb tumani",
    },
  },
  {
    region: "Qoraqalpog'iston",
    districts: {
      nukus: "Nukus tumani",
      qoshkopir: "Qoshkopir tumani",
      tortkul: "Tortkul tumani",
      boqishoq: "Boqishoq tumani",
      tuzkon: "Tuzkon tumani",
      muynak: "Muynak tumani",
      chimboy: "Chimboy tumani",
      shumanay: "Shumanay tumani",
    },
  },
];
